---
- name: Prepare and run Terraform
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure openstack config directory exists
      file:
        path: /home/semaphore/.config/openstack
        state: directory
        mode: '0755'
        recurse: yes

    # clouds.yaml 생성하는 task 제거됨

    - name: Clone Terraform code from GitHub
      git:
        repo: https://github.com/flekke/semaphore-projects.git
        dest: /tmp/tf-project
        version: main
        force: yes
      environment:
        GIT_TERMINAL_PROMPT: "0"

    - name: Run terraform init
      shell: terraform init
      args:
        chdir: /tmp/tf-project/terraform
      environment:
        OS_CLIENT_CONFIG_FILE: /home/semaphore/.config/openstack/clouds.yaml

    - name: Run terraform apply
      shell: terraform apply -auto-approve
      args:
        chdir: /tmp/tf-project/terraform
      environment:
        OS_CLIENT_CONFIG_FILE: /home/semaphore/.config/openstack/clouds.yaml

    - name: Get instance IPs from Terraform output
      command: terraform output -json instance_ips
      register: tf_output
      args:
        chdir: /tmp/tf-project/terraform

    - name: Generate inventory.ini content from Terraform output
      set_fact:
        inventory_content: |
          {% set ips = tf_output.stdout | from_json %}
          {% for name, ip in ips.items() %}
{{ ip }} ansible_user=ubuntu ansible_become=true{% if name == 'node1' %} etcd_member_name=etcd1{% endif %}
          {% endfor %}

[kube_control_plane]
{{ ips['node1'] }}

[etcd:children]
kube_control_plane

[kube_node]
{{ ips['node2'] }}
{{ ips['node3'] }}

    
    - name: Write inventory.ini to file
      copy:
        content: "{{ inventory_content }}"
        dest: /tmp/tf-project/kubespray-inventory.ini
